[tool.poetry]
name = "ml-repo"
version = "0.1.0"
description = "A Python machine learning repository"
authors = ["Your Name <your@email.com>"]

[tool.poetry.dependencies]
python = "^3.9"
torch = "^1.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
